const fs = require('fs');
const http = require('http');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const { spawn, spawnSync } = require('child_process');
const sqliteStore = require('./inc/visualwavedrom-sqlite-node.js');

function commandLineOption(name) {
  const index = process.argv.indexOf(name);
  if (index < 0) return null;
  const value = process.argv[index + 1];
  if (!value || value.startsWith('--')) throw new Error(`Missing value for ${name}`);
  return value;
}

const rootDir = __dirname;
const rootRealDir = fs.realpathSync(rootDir);
const importRootDir = path.join(rootDir, 'import');
const importSchemeDir = path.join(importRootDir, 'Scheme');
const importFileProcPath = path.join(importRootDir, 'inc', 'fileProc.py');
const importMaxOutputBytes = 64 * 1024 * 1024;
const importMaxWaveColumns = 10 * 1000 * 1000;
const importMaxUploadBytes = 128 * 1024 * 1024;
const importSampleLineLimit = 5;
const defaultHtmlName = `${path.basename(__filename, '.js')}.html`;
const configuredHtmlName = commandLineOption('--html') || defaultHtmlName;
const htmlName = path.basename(configuredHtmlName);
if (htmlName !== configuredHtmlName || !/\.html?$/i.test(htmlName)) {
  throw new Error(`Invalid HTML file name: ${configuredHtmlName}`);
}
const htmlPath = path.join(rootDir, htmlName);
const defaultLibraryName = `${path.basename(__filename, '.js')}-library`;
const appId = 'VisualWaveDrom';
const libraryKind = sqliteStore.LIBRARY_KIND;
const maxWaveLibraryRequestBytes = 256 * 1024 * 1024;
const protocolScheme = 'visualwavedrom';
let activeProtocolScheme = protocolScheme;
const configuredLibraryOption = commandLineOption('--library');
const configuredLibraryCandidate = configuredLibraryOption
  ? path.resolve(rootDir, configuredLibraryOption)
  : path.join(rootDir, 'Wave', defaultLibraryName, 'library.sqlite');
const configuredCandidateExtension = path.extname(configuredLibraryCandidate).toLowerCase();
if (configuredCandidateExtension !== '.sqlite') {
  throw new Error(`Wave library must be a .sqlite file: ${configuredLibraryOption || configuredLibraryCandidate}`);
}
const configuredLibraryPath = configuredLibraryCandidate;
const configuredLibraryIsFolderDatabase = path.basename(configuredLibraryPath).toLowerCase() === 'library.sqlite';
const configuredLibraryDirectory = path.dirname(configuredLibraryPath);
const waveDir = configuredLibraryIsFolderDatabase
  ? path.dirname(configuredLibraryDirectory)
  : path.dirname(configuredLibraryPath);
const serviceStatePath = path.join(waveDir, '.visualwavedrom-state.json');
const configuredLibraryName = configuredLibraryIsFolderDatabase
  ? path.basename(configuredLibraryDirectory)
  : path.basename(configuredLibraryPath, path.extname(configuredLibraryPath));
const requestedOpenUrl = commandLineOption('--open-url');
const protocolHandlerPath = commandLineOption('--protocol-handler');
const defaultPort = 4173;
const configuredPort = Number(process.env.PORT);
const preferredPort = Number.isInteger(configuredPort) && configuredPort >= 1 && configuredPort <= 65535
  ? configuredPort
  : defaultPort;
const noOpen = process.argv.includes('--no-open');
let shutdownTimer = null;
let requestedPort = preferredPort;
let selectingFallbackPort = false;
let sqliteRuntimeInfo = null;
let pythonRuntimeInfo = null;
let pythonRuntimeChecked = false;
const connectedClients = new Set();
const defaultWaveDocument = `${JSON.stringify({
  signal: [
    { name: 'clk', wave: 'p.....|', node: '.a....|' },
    { name: 'dat', wave: 'x.345x|=', data: ['head', 'body', 'tail', 'data'], node: '....b...' },
    { name: 'bus', wave: 'x.34.5x|......', data: ['write', 'read', 'data'] },
    { name: 'wire', wave: '0.1..0.|1.0' },
    { name: 'err', wave: 'x.....|' }
  ],
  edge: ['a->b'],
  head: { text: 'WaveDrom Example' },
  foot: { text: 'Generated by VisualWaveDrom' },
  config: { hscale: 1 }
}, null, 2)}\n`;

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function newStableId(prefix) {
  return `${prefix}-${crypto.randomUUID()}`;
}

function writeJsonAtomically(filePath, value) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const tempPath = `${filePath}.${process.pid}.tmp`;
  fs.writeFileSync(tempPath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
  fs.renameSync(tempPath, filePath);
}

function writeTextAtomically(filePath, value, mode) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const tempPath = `${filePath}.${process.pid}.tmp`;
  fs.writeFileSync(tempPath, String(value), { encoding: 'utf8', mode: mode || 0o644 });
  fs.renameSync(tempPath, filePath);
}

function readRecentLibraryName() {
  try {
    const state = readJson(serviceStatePath);
    const name = String(state && state.recentLibrary || '');
    return name && path.basename(name) === name ? name : '';
  } catch (_) {
    return '';
  }
}

function rememberLibraryName(name) {
  const libraryName = String(name || '');
  if (!libraryName || path.basename(libraryName) !== libraryName) return false;
  if (readRecentLibraryName() === libraryName) return true;
  try {
    writeJsonAtomically(serviceStatePath, {
      version: 1,
      recentLibrary: libraryName,
      updatedAt: new Date().toISOString()
    });
    return true;
  } catch (error) {
    console.warn(`Could not remember the selected wave library: ${error.message}`);
    return false;
  }
}

function libraryNameFromPath(filePath) {
  if (path.resolve(filePath) === path.resolve(configuredLibraryPath)) return configuredLibraryName;
  return path.basename(filePath).toLowerCase() === 'library.sqlite'
    ? path.basename(path.dirname(filePath))
    : path.basename(filePath, path.extname(filePath));
}

function normalizeLibraryIdentity(library) {
  let changed = false;
  if (!library.libraryId || typeof library.libraryId !== 'string') {
    library.libraryId = newStableId('library');
    changed = true;
  }
  if (!Number.isInteger(library.version) || library.version < 2) {
    library.version = 2;
    changed = true;
  }
  library.documents.forEach((document) => {
    if (!document || typeof document !== 'object') return;
    if (!Number.isInteger(document.revision) || document.revision < 0) {
      document.revision = 0;
      changed = true;
    }
  });
  return changed;
}

function ensureWaveDirectory() {
  fs.mkdirSync(waveDir, { recursive: true });
  const defaultPath = configuredLibraryPath;
  if (fs.existsSync(defaultPath)) {
    if (!sqliteStore.isLibraryFile(defaultPath)) {
      throw new Error(`Invalid SQLite wave library: ${defaultPath}`);
    }
    return;
  }

  const library = {
    kind: libraryKind,
    version: 2,
    libraryId: newStableId('library'),
    updatedAt: new Date().toISOString(),
    documents: [{
      name: 'default-wave',
      content: defaultWaveDocument,
      hscale: 1,
      waveEditMode: 'modify',
      revision: 0,
      savedAt: new Date().toISOString()
    }],
    directories: [],
    activeDocumentName: 'default-wave',
    selectedDirectoryId: 'nav-root'
  };
  sqliteStore.writeLibrary(defaultPath, library);
}

function listLibraries() {
  ensureWaveDirectory();
  const libraries = fs.readdirSync(waveDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => ({ name: entry.name, filePath: path.join(waveDir, entry.name, 'library.sqlite') }))
    .filter(({ filePath }) => fs.existsSync(filePath))
    .filter(({ filePath }) => sqliteStore.isLibraryFile(filePath))
    .map(({ name, filePath }) => {
      const info = sqliteStore.getLibraryInfo(filePath);
      return {
        name,
        libraryId: info.libraryId,
        documentCount: info.documentCount,
        mtimeMs: fs.statSync(filePath).mtimeMs
      };
    });
  if (fs.existsSync(configuredLibraryPath)
      && sqliteStore.isLibraryFile(configuredLibraryPath)
      && !libraries.some((library) => library.name === configuredLibraryName)) {
    const info = sqliteStore.getLibraryInfo(configuredLibraryPath);
    libraries.push({
      name: configuredLibraryName,
      libraryId: info.libraryId,
      documentCount: info.documentCount,
      mtimeMs: fs.statSync(configuredLibraryPath).mtimeMs
    });
  }
  return libraries.sort((a, b) => b.mtimeMs - a.mtimeMs);
}

function safeLibraryPath(libraryName) {
  const requested = String(libraryName || '');
  const name = path.basename(requested);
  if (!name
      || name !== requested
      || name === '.'
      || name === '..'
      || /[\\/\u0000-\u001f]/.test(name)) return null;
  if (name === configuredLibraryName) return configuredLibraryPath;
  return path.join(waveDir, name, 'library.sqlite');
}

function libraryPathById(libraryId) {
  const id = String(libraryId || '').trim();
  if (!id) return null;
  const item = listLibraries().find((library) => library.libraryId === id);
  return item ? safeLibraryPath(item.name) : null;
}

function contentType(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  return ({ '.html': 'text/html; charset=utf-8', '.js': 'application/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.wasm': 'application/wasm', '.svg': 'image/svg+xml', '.png': 'image/png', '.ico': 'image/x-icon' }[ext] || 'application/octet-stream');
}

function sendJson(res, status, payload) {
  res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8' });
  res.end(JSON.stringify(payload));
}

function readRequestBody(req, maxBytes) {
  return new Promise((resolve, reject) => {
    let body = '';
    req.setEncoding('utf8');
    req.on('data', (part) => {
      body += part;
      if (body.length > maxBytes) {
        reject(new Error('Request body is too large'));
        req.destroy();
      }
    });
    req.on('end', () => resolve(body));
    req.on('error', reject);
  });
}

function readRequestBuffer(req, maxBytes) {
  return new Promise((resolve, reject) => {
    const declaredLength = Number(req.headers['content-length'] || 0);
    if (Number.isFinite(declaredLength) && declaredLength > maxBytes) {
      reject(new Error('Uploaded waveform data file is too large'));
      return;
    }
    const chunks = [];
    let totalBytes = 0;
    let settled = false;
    const finish = (error, value) => {
      if (settled) return;
      settled = true;
      if (error) reject(error);
      else resolve(value);
    };
    req.on('data', (part) => {
      const chunk = Buffer.isBuffer(part) ? part : Buffer.from(part);
      totalBytes += chunk.length;
      if (totalBytes > maxBytes) {
        finish(new Error('Uploaded waveform data file is too large'));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on('end', () => finish(null, Buffer.concat(chunks, totalBytes)));
    req.on('error', (error) => finish(error));
  });
}

function normalizedRoot(value) {
  const resolved = path.resolve(String(value || ''));
  return process.platform === 'win32' ? resolved.toLowerCase() : resolved;
}

function quoteWindowsCommandArgument(value) {
  const text = String(value == null ? '' : value);
  if (text.includes('"')) throw new Error('Windows command arguments cannot contain quotes');
  return `"${text}"`;
}

function refreshActiveProtocolScheme() {
  const library = sqliteStore.readLibrarySummary(configuredLibraryPath);
  const librarySuffix = String(library.libraryId || '')
    .toLowerCase()
    .replace(/[^a-z0-9+.-]/g, '-');
  activeProtocolScheme = librarySuffix ? `${protocolScheme}-${librarySuffix}` : protocolScheme;
}

function registerWindowsProtocolHandler(resolved) {
  if (path.extname(resolved).toLowerCase() !== '.bat') {
    console.warn(`Protocol handler BAT not found: ${resolved}`);
    return;
  }
  const command = [
    quoteWindowsCommandArgument(process.execPath),
    quoteWindowsCommandArgument(__filename),
    '--html',
    quoteWindowsCommandArgument(htmlName),
    '--library',
    quoteWindowsCommandArgument(configuredLibraryPath),
    '--protocol-handler',
    quoteWindowsCommandArgument(resolved),
    '--open-url',
    '"%1"'
  ].join(' ');
  const schemes = Array.from(new Set([activeProtocolScheme, protocolScheme]));
  const commands = schemes.flatMap((scheme) => {
    const key = `HKCU\\Software\\Classes\\${scheme}`;
    return [
      ['add', key, '/ve', '/d', 'URL:VisualWaveDrom Protocol', '/f'],
      ['add', key, '/v', 'URL Protocol', '/t', 'REG_SZ', '/f'],
      ['add', `${key}\\DefaultIcon`, '/ve', '/d', `"${htmlPath}",0`, '/f'],
      ['add', `${key}\\shell\\open\\command`, '/ve', '/d', command, '/f']
    ];
  });
  const results = commands.map((args) => spawnSync('reg.exe', args, { stdio: 'ignore' }));
  const failed = results.some((result) => result.status !== 0);
  if (failed) console.warn('Could not register the VisualWaveDrom URL protocol.');
}

function quoteDesktopExecArgument(value) {
  const text = String(value == null ? '' : value)
    .replace(/\\/g, '\\\\\\\\')
    .replace(/"/g, '\\"')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$')
    .replace(/%/g, '%%');
  return `"${text}"`;
}

function escapeDesktopString(value) {
  return String(value == null ? '' : value)
    .replace(/\\/g, '\\\\')
    .replace(/[\r\n\t]+/g, ' ')
    .trim();
}

function registerLinuxProtocolHandler(resolved) {
  if (path.extname(resolved).toLowerCase() !== '.sh') {
    console.warn(`Protocol handler shell script not found: ${resolved}`);
    return;
  }
  if (/[\u0000\r\n]/.test(resolved)) {
    console.warn('Protocol handler path contains unsupported control characters.');
    return;
  }
  const configuredHome = String(process.env.HOME || '').trim();
  const detectedHome = String(os.homedir() || '').trim();
  const homeDirectory = path.isAbsolute(configuredHome)
    ? configuredHome
    : (path.isAbsolute(detectedHome) ? detectedHome : '');
  if (!homeDirectory) {
    console.warn('Could not register the VisualWaveDrom URL protocol: HOME is not set.');
    return;
  }
  const configuredDataHome = String(process.env.XDG_DATA_HOME || '').trim();
  const dataHome = path.isAbsolute(configuredDataHome)
    ? configuredDataHome
    : path.join(homeDirectory, '.local', 'share');
  const applicationsDirectory = path.join(dataHome, 'applications');
  const desktopFileName = `${activeProtocolScheme.replace(/[^a-z0-9+.-]/g, '-')}.desktop`;
  const desktopPath = path.join(applicationsDirectory, desktopFileName);
  const schemes = Array.from(new Set([activeProtocolScheme, protocolScheme]));
  const displayName = escapeDesktopString(configuredLibraryName);
  const desktopEntry = [
    '[Desktop Entry]',
    'Version=1.0',
    'Type=Application',
    `Name=VisualWaveDrom${displayName ? ` - ${displayName}` : ''}`,
    `Exec=bash ${quoteDesktopExecArgument(resolved)} %u`,
    'Terminal=true',
    'NoDisplay=true',
    'StartupNotify=false',
    'Categories=Development;Utility;',
    `MimeType=${schemes.map((scheme) => `x-scheme-handler/${scheme};`).join('')}`,
    ''
  ].join('\n');

  try {
    writeTextAtomically(desktopPath, desktopEntry, 0o644);
  } catch (error) {
    console.warn(`Could not write the VisualWaveDrom desktop entry: ${error.message}`);
    return;
  }
  if (!process.env.DISPLAY && !process.env.WAYLAND_DISPLAY) {
    console.log('Linux URL protocol registration will finish on the next desktop-session launch.');
    return;
  }

  const desktopDatabaseUpdate = spawnSync(
    'update-desktop-database',
    [applicationsDirectory],
    { stdio: 'ignore', timeout: 5000 }
  );
  if (desktopDatabaseUpdate.error && desktopDatabaseUpdate.error.code !== 'ENOENT') {
    console.warn(`Could not refresh desktop entries: ${desktopDatabaseUpdate.error.message}`);
  }
  const registrations = schemes.map((scheme) => spawnSync(
    'xdg-mime',
    ['default', desktopFileName, `x-scheme-handler/${scheme}`],
    { stdio: 'ignore', timeout: 5000 }
  ));
  const missingXdgMime = registrations.some(
    (result) => result.error && result.error.code === 'ENOENT'
  );
  const failed = registrations.some((result) => result.error || result.status !== 0);
  if (missingXdgMime) {
    console.warn('xdg-mime is unavailable; automatic VisualWaveDrom links were not registered.');
    return;
  }
  if (failed) {
    console.warn('Could not register the VisualWaveDrom URL protocol with xdg-mime.');
  }
}

function registerProtocolHandler(handlerPath) {
  refreshActiveProtocolScheme();
  if (!handlerPath) return;
  const resolved = path.resolve(handlerPath);
  if (!fs.existsSync(resolved) || !fs.statSync(resolved).isFile()) {
    console.warn(`Protocol handler not found: ${resolved}`);
    return;
  }
  if (process.platform === 'win32') {
    registerWindowsProtocolHandler(resolved);
  } else if (process.platform === 'linux') {
    registerLinuxProtocolHandler(resolved);
  }
}

function requestedPagePath(rawUrl) {
  if (!rawUrl) return `/${htmlName}`;
  try {
    const requestUrl = new URL(rawUrl);
    if (requestUrl.protocol !== `${protocolScheme}:`
        && requestUrl.protocol !== `${activeProtocolScheme}:`) return `/${htmlName}`;
    const params = new URLSearchParams();
    ['libraryId', 'waveId', 'view'].forEach((name) => {
      const value = requestUrl.searchParams.get(name);
      if (value) params.set(name, value);
    });
    if (!params.has('view')) params.set('view', 'single');
    return `/open?${params.toString()}`;
  } catch (_) {
    return `/${htmlName}`;
  }
}

function probeServerInfo(port) {
  return new Promise((resolve) => {
    let settled = false;
    const finish = (value) => {
      if (settled) return;
      settled = true;
      resolve(value);
    };
    const request = http.get({
      hostname: '127.0.0.1',
      port,
      path: '/api/server-info',
      timeout: 800
    }, (response) => {
      let body = '';
      response.setEncoding('utf8');
      response.on('data', (part) => {
        body += part;
        if (body.length > 64 * 1024) {
          request.destroy();
          finish(null);
        }
      });
      response.on('error', () => finish(null));
      response.on('end', () => {
        if (response.statusCode !== 200) { finish(null); return; }
        try {
          finish(JSON.parse(body));
        } catch (_) {
          finish(null);
        }
      });
    });
    request.on('timeout', () => {
      request.destroy();
      finish(null);
    });
    request.on('error', () => finish(null));
  });
}

function pageAddress(port, rawUrl) {
  return `http://127.0.0.1:${port}${requestedPagePath(rawUrl)}`;
}

function openAddress(address) {
  if (noOpen) return;
  if (process.platform === 'linux'
      && !process.env.DISPLAY
      && !process.env.WAYLAND_DISPLAY) {
    console.log('No Linux desktop session was detected; open the printed URL manually.');
    return;
  }
  let target;
  try {
    target = new URL(address);
    if (!/^https?:$/.test(target.protocol) || target.hostname !== '127.0.0.1') {
      throw new Error('Only local VisualWaveDrom HTTP addresses may be opened');
    }
  } catch (error) {
    console.warn(`Could not open the browser automatically: ${error.message}`);
    return;
  }

  let openers;
  if (process.platform === 'win32') {
    openers = [['rundll32.exe', ['url.dll,FileProtocolHandler', target.href]]];
  } else if (process.platform === 'darwin') {
    openers = [['open', [target.href]]];
  } else {
    openers = [
      ['xdg-open', [target.href]],
      ['gio', ['open', target.href]],
      ['sensible-browser', [target.href]]
    ];
  }

  const launchOpener = (index) => {
    if (index >= openers.length) {
      console.warn('Could not open the browser automatically; open the printed URL manually.');
      return;
    }
    const [command, args] = openers[index];
    const opener = spawn(command, args, {
      detached: true,
      stdio: 'ignore',
      windowsHide: true,
      shell: false
    });
    opener.once('error', () => launchOpener(index + 1));
    opener.unref();
  };
  launchOpener(0);
}

function pathIsInsideRoot(rootPath, targetPath) {
  const relative = path.relative(rootPath, targetPath);
  return relative === ''
    || (relative !== '..'
      && !relative.startsWith(`..${path.sep}`)
      && !path.isAbsolute(relative));
}

function probePythonCandidate(command, prefixArgs) {
  const result = spawnSync(
    command,
    (prefixArgs || []).concat(['-c', 'import sys; print("%d.%d.%d" % sys.version_info[:3])']),
    {
      encoding: 'utf8',
      timeout: 5000,
      windowsHide: true,
      shell: false
    }
  );
  if (result.error || result.status !== 0) return null;
  const match = String(result.stdout || '').trim().match(/^(\d+)\.(\d+)\.(\d+)/);
  if (!match) return null;
  const major = Number(match[1]);
  const minor = Number(match[2]);
  if (major < 3 || (major === 3 && minor < 6)) return null;
  return {
    available: true,
    command,
    prefixArgs: (prefixArgs || []).slice(),
    version: `${match[1]}.${match[2]}.${match[3]}`
  };
}

function getPythonRuntimeInfo() {
  if (pythonRuntimeChecked) return pythonRuntimeInfo;
  pythonRuntimeChecked = true;
  const candidates = [];
  const configuredPython = String(process.env.VWD_PYTHON_EXE || '').trim();
  if (configuredPython) candidates.push({ command: configuredPython, prefixArgs: [] });
  if (process.platform === 'win32') {
    candidates.push(
      { command: path.join(importRootDir, 'python-runtime', 'python.exe'), prefixArgs: [] },
      { command: 'py.exe', prefixArgs: ['-3'] },
      { command: 'python.exe', prefixArgs: [] },
      { command: 'python3.exe', prefixArgs: [] }
    );
  } else {
    candidates.push(
      { command: path.join(importRootDir, 'python-runtime', 'bin', 'python3'), prefixArgs: [] },
      { command: 'python3', prefixArgs: [] },
      { command: 'python', prefixArgs: [] }
    );
  }
  for (const candidate of candidates) {
    if (path.isAbsolute(candidate.command) && !fs.existsSync(candidate.command)) continue;
    const runtime = probePythonCandidate(candidate.command, candidate.prefixArgs);
    if (runtime) {
      pythonRuntimeInfo = runtime;
      return pythonRuntimeInfo;
    }
  }
  pythonRuntimeInfo = {
    available: false,
    version: '',
    error: 'Python 3.6 or newer was not found'
  };
  return pythonRuntimeInfo;
}

function resolveImportSourcePath(fileName) {
  const sourceName = String(fileName || '').trim();
  if (!sourceName || path.isAbsolute(sourceName) || /[\u0000\r\n]/.test(sourceName)) {
    throw new Error(`Invalid import source file: ${sourceName || '(empty)'}`);
  }
  const slashPath = sourceName.replace(/\\/g, '/').replace(/^\.\/+/, '');
  const relativePath = slashPath.toLowerCase().startsWith('import/')
    ? slashPath.slice('import/'.length)
    : slashPath;
  const resolved = path.resolve(importRootDir, relativePath);
  if (!pathIsInsideRoot(importRootDir, resolved)) {
    throw new Error(`Import source must stay inside the import folder: ${sourceName}`);
  }
  if (!fs.existsSync(resolved) || !fs.statSync(resolved).isFile()) {
    throw new Error(`Import source file not found: ${sourceName}`);
  }
  const importRealDir = fs.realpathSync(importRootDir);
  const realSource = fs.realpathSync(resolved);
  if (!pathIsInsideRoot(importRealDir, realSource)) {
    throw new Error(`Import source must stay inside the import folder: ${sourceName}`);
  }
  return realSource;
}

function normalizeImportScheme(rawScheme, schemeId) {
  if (!rawScheme || typeof rawScheme !== 'object' || Array.isArray(rawScheme)) {
    throw new Error('Import scheme must contain a JSON object');
  }
  const rawMappings = Array.isArray(rawScheme.mappings)
    ? rawScheme.mappings
    : (Array.isArray(rawScheme.imports)
      ? rawScheme.imports
      : (Array.isArray(rawScheme.entries) ? rawScheme.entries : null));
  if (!rawMappings || rawMappings.length === 0) {
    throw new Error('Import scheme must contain at least one mapping');
  }
  const seenSignals = new Set();
  const mappings = rawMappings.map((rawMapping, index) => {
    if (!rawMapping || typeof rawMapping !== 'object' || Array.isArray(rawMapping)) {
      throw new Error(`Mapping ${index + 1} must be an object`);
    }
    const signal = String(rawMapping.signal || '').trim();
    const parser = String(rawMapping.parser || rawMapping.function || '').trim();
    const file = String(rawMapping.file || '').trim();
    if (!signal) throw new Error(`Mapping ${index + 1} is missing signal`);
    if (seenSignals.has(signal)) throw new Error(`Signal is mapped more than once: ${signal}`);
    seenSignals.add(signal);
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(parser)) {
      throw new Error(`Mapping ${index + 1} has an invalid parser function`);
    }
    const options = rawMapping.options == null ? {} : rawMapping.options;
    if (!options || typeof options !== 'object' || Array.isArray(options)) {
      throw new Error(`Mapping ${index + 1} options must be an object`);
    }
    const sourcePath = resolveImportSourcePath(file);
    return {
      file,
      signal,
      parser,
      options,
      sourcePath,
      displayPath: path.relative(rootDir, sourcePath).split(path.sep).join('/')
    };
  });
  return {
    id: schemeId,
    version: Number.isInteger(rawScheme.version) ? rawScheme.version : 1,
    name: String(rawScheme.name || path.basename(schemeId, path.extname(schemeId))).trim(),
    description: String(rawScheme.description || '').trim(),
    mappings
  };
}

function safeImportSchemePath(schemeId) {
  const requested = String(schemeId || '').trim();
  const fileName = path.basename(requested);
  if (!requested
      || requested !== fileName
      || !/\.json$/i.test(fileName)
      || /[\u0000-\u001f]/.test(fileName)) {
    throw new Error('Invalid import scheme id');
  }
  const schemePath = path.join(importSchemeDir, fileName);
  if (!fs.existsSync(schemePath) || !fs.statSync(schemePath).isFile()) {
    throw new Error(`Import scheme not found: ${fileName}`);
  }
  const schemeRealDir = fs.realpathSync(importSchemeDir);
  const realSchemePath = fs.realpathSync(schemePath);
  if (!pathIsInsideRoot(schemeRealDir, realSchemePath)) {
    throw new Error(`Import scheme must stay inside import/Scheme: ${fileName}`);
  }
  return realSchemePath;
}

function loadImportScheme(schemeId) {
  const schemePath = safeImportSchemePath(schemeId);
  return normalizeImportScheme(readJson(schemePath), path.basename(schemePath));
}

function publicImportScheme(scheme) {
  return {
    id: scheme.id,
    version: scheme.version,
    name: scheme.name,
    description: scheme.description,
    mappings: scheme.mappings.map((mapping, mappingIndex) => ({
      mappingIndex,
      file: mapping.displayPath,
      signal: mapping.signal,
      parser: mapping.parser,
      options: Object.assign({}, mapping.options)
    }))
  };
}

function listImportSchemes() {
  if (!fs.existsSync(importSchemeDir)) return { schemes: [], invalid: [] };
  const schemes = [];
  const invalid = [];
  fs.readdirSync(importSchemeDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && /\.json$/i.test(entry.name))
    .sort((a, b) => a.name.localeCompare(b.name))
    .forEach((entry) => {
      try {
        schemes.push(publicImportScheme(loadImportScheme(entry.name)));
      } catch (error) {
        invalid.push({ id: entry.name, error: error.message });
      }
    });
  return { schemes, invalid };
}

function countDelimitedColumns(line, delimiter) {
  if (!delimiter) return 1;
  let count = 1;
  let quoted = false;
  for (let index = 0; index < line.length; index++) {
    const char = line[index];
    if (char === '"') {
      if (quoted && line[index + 1] === '"') index += 1;
      else quoted = !quoted;
    } else if (!quoted && char === delimiter) {
      count += 1;
    }
  }
  return count;
}

function splitImportSampleColumns(line, delimiterKind) {
  const text = String(line || '').trim();
  if (delimiterKind === 'tab') return text.split('\t').map((value) => value.trim());
  if (delimiterKind === 'comma') {
    const columns = [];
    let value = '';
    let quoted = false;
    for (let index = 0; index < text.length; index++) {
      const char = text[index];
      if (char === '"') {
        if (quoted && text[index + 1] === '"') {
          value += '"';
          index += 1;
        } else {
          quoted = !quoted;
        }
      } else if (!quoted && char === ',') {
        columns.push(value.trim());
        value = '';
      } else {
        value += char;
      }
    }
    columns.push(value.trim());
    return columns;
  }
  if (delimiterKind === 'whitespace') return text.split(/\s+/);
  return [text];
}

function normalizeImportSampleLines(payload) {
  const supplied = payload && Array.isArray(payload.sampleLines)
    ? payload.sampleLines
    : String(payload && payload.sampleText || '').split(/\r?\n/);
  return supplied
    .slice(0, importSampleLineLimit)
    .map((line) => String(line == null ? '' : line).slice(0, 4096));
}

function analyzeImportSample(fileName, suppliedLines) {
  const firstLines = suppliedLines.slice(0, importSampleLineLimit);
  const meaningfulLines = firstLines
    .map((line) => String(line || '').trim())
    .filter((line) => line && !line.startsWith('#') && !line.startsWith('//'));
  if (!meaningfulLines.length) {
    return {
      firstLines,
      meaningfulLineCount: 0,
      delimiter: 'unknown',
      delimiterLabel: '无法判断',
      columnCount: 0,
      explicitIndex: false,
      headerLikely: false,
      recommendedParser: 'parse_index_data',
      reason: '前 5 行没有可分析的数据，建议先尝试通用序号/数据解析函数'
    };
  }

  const extension = path.extname(String(fileName || '')).toLowerCase();
  const tabColumns = meaningfulLines.map((line) => countDelimitedColumns(line, '\t'));
  const commaColumns = meaningfulLines.map((line) => countDelimitedColumns(line, ','));
  let delimiter = 'single';
  if (tabColumns.some((count) => count > 1)
      && tabColumns.filter((count) => count > 1).length
        >= commaColumns.filter((count) => count > 1).length) {
    delimiter = 'tab';
  } else if (commaColumns.some((count) => count > 1)) {
    delimiter = 'comma';
  } else if (meaningfulLines.some((line) => /\s+/.test(line.trim()))) {
    delimiter = 'whitespace';
  } else if (extension === '.csv') {
    delimiter = 'comma';
  } else if (extension === '.tsv') {
    delimiter = 'tab';
  }

  const rows = meaningfulLines.map((line) => splitImportSampleColumns(line, delimiter));
  const columnCount = rows.reduce((maximum, columns) => Math.max(maximum, columns.length), 0);
  const isIndex = (value) => /^\+?\d+$/.test(String(value || '').trim());
  const headerLikely = rows.length > 1
    && rows[0].length > 1
    && !isIndex(rows[0][0])
    && rows.slice(1).every((columns) => columns.length > 1 && isIndex(columns[0]));
  const dataRows = headerLikely ? rows.slice(1) : rows;
  let previousIndex = -1;
  const explicitIndex = columnCount > 1
    && dataRows.length > 0
    && dataRows.every((columns) => {
      if (columns.length < 2 || !isIndex(columns[0])) return false;
      const index = Number(columns[0]);
      if (index <= previousIndex) return false;
      previousIndex = index;
      return true;
    });

  let recommendedParser = 'parse_index_data';
  if (columnCount <= 1) recommendedParser = 'parse_single_column';
  else if (delimiter === 'comma') recommendedParser = 'parse_csv_index_data';
  else if (delimiter === 'tab') recommendedParser = 'parse_tsv_index_data';

  const delimiterLabels = {
    single: '单列',
    comma: '逗号分隔',
    tab: 'Tab 分隔',
    whitespace: '空白分隔'
  };
  const details = [
    delimiterLabels[delimiter] || '未知格式',
    columnCount + ' 列'
  ];
  if (explicitIndex) details.push('第一列为递增序号');
  else if (columnCount > 1) details.push('第一列未完全匹配递增序号');
  if (headerLikely) details.push('首行可能是表头');

  return {
    firstLines,
    meaningfulLineCount: meaningfulLines.length,
    delimiter,
    delimiterLabel: delimiterLabels[delimiter] || '未知格式',
    columnCount,
    explicitIndex,
    headerLikely,
    recommendedParser,
    reason: '检测到' + details.join('，') + '，建议使用 ' + recommendedParser
  };
}

function importParserCompatibilityScore(parser, analysis) {
  if (parser === analysis.recommendedParser) return 100;
  if (parser === 'parse_index_data') return 75;
  if (analysis.recommendedParser === 'parse_index_data'
      && (parser === 'parse_csv_index_data' || parser === 'parse_tsv_index_data')) {
    return 45;
  }
  return 10;
}

function recommendImportScheme(schemes, analysis) {
  let recommended = null;
  schemes.forEach((scheme) => {
    (scheme.mappings || []).forEach((mapping, mappingIndex) => {
      let score = importParserCompatibilityScore(mapping.parser, analysis);
      const options = mapping.options || {};
      if (analysis.headerLikely && Number(options.skipRows || 0) > 0) score += 8;
      if (analysis.delimiter === 'comma' && options.delimiter === 'comma') score += 5;
      if (analysis.delimiter === 'tab' && options.delimiter === 'tab') score += 5;
      if (!recommended || score > recommended.score) {
        recommended = {
          schemeId: scheme.id,
          schemeName: scheme.name,
          mappingIndex: Number.isInteger(mapping.mappingIndex)
            ? mapping.mappingIndex
            : mappingIndex,
          parser: mapping.parser,
          score
        };
      }
    });
  });
  return recommended;
}

function analyzeImportFileRequest(payload) {
  const catalog = listImportSchemes();
  const analysis = analyzeImportSample(
    String(payload && payload.fileName || ''),
    normalizeImportSampleLines(payload)
  );
  return {
    analysis,
    recommended: recommendImportScheme(catalog.schemes, analysis),
    schemes: catalog.schemes,
    invalid: catalog.invalid
  };
}

function runImportParser(mapping, runtime) {
  return new Promise((resolve, reject) => {
    if (!fs.existsSync(importFileProcPath)) {
      reject(new Error('import/inc/fileProc.py was not found'));
      return;
    }
    const args = runtime.prefixArgs.concat([
      importFileProcPath,
      '--parser', mapping.parser,
      '--file', mapping.sourcePath,
      '--options-json', JSON.stringify(mapping.options)
    ]);
    const child = spawn(runtime.command, args, {
      cwd: rootDir,
      windowsHide: true,
      shell: false,
      stdio: ['ignore', 'pipe', 'pipe']
    });
    let stdout = '';
    let stderr = '';
    let outputTooLarge = false;
    let settled = false;
    let outputBytes = 0;
    let timeout = null;
    const finish = (error, value) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      if (error) reject(error);
      else resolve(value);
    };
    const appendOutput = (current, chunk) => {
      const text = String(chunk);
      outputBytes += Buffer.byteLength(text, 'utf8');
      if (outputBytes > importMaxOutputBytes) {
        outputTooLarge = true;
        child.kill();
      }
      return current + text;
    };
    child.stdout.setEncoding('utf8');
    child.stderr.setEncoding('utf8');
    child.stdout.on('data', (chunk) => { stdout = appendOutput(stdout, chunk); });
    child.stderr.on('data', (chunk) => { stderr = appendOutput(stderr, chunk); });
    child.once('error', (error) => finish(new Error(`Could not start Python: ${error.message}`)));
    child.once('close', (code) => {
      if (outputTooLarge) {
        finish(new Error(`Import output is larger than ${importMaxOutputBytes} bytes`));
        return;
      }
      if (code !== 0) {
        finish(new Error(String(stderr || stdout || `Python parser exited with code ${code}`).trim()));
        return;
      }
      let result;
      try {
        result = JSON.parse(stdout);
      } catch (error) {
        finish(new Error(`Python parser returned invalid JSON: ${error.message}`));
        return;
      }
      if (!result || typeof result.wave !== 'string' || !Array.isArray(result.data)) {
        finish(new Error('Python parser result must contain wave and data'));
        return;
      }
      if (result.wave.length > importMaxWaveColumns) {
        finish(new Error(`Imported waveform exceeds ${importMaxWaveColumns} columns`));
        return;
      }
      result.data = result.data.map((value) => String(value == null ? '' : value));
      finish(null, result);
    });
    timeout = setTimeout(() => {
      child.kill();
      finish(new Error('Python parser timed out after 60 seconds'));
    }, 60000);
  });
}

async function runImportScheme(schemeId) {
  const runtime = getPythonRuntimeInfo();
  if (!runtime.available) throw new Error(runtime.error);
  const scheme = loadImportScheme(schemeId);
  const updates = [];
  for (const mapping of scheme.mappings) {
    const result = await runImportParser(mapping, runtime);
    updates.push({
      signal: mapping.signal,
      wave: result.wave,
      data: result.data,
      sourceFile: mapping.displayPath,
      parser: mapping.parser,
      pointCount: Number(result.pointCount || 0),
      firstIndex: Number(result.firstIndex || 0),
      lastIndex: Number(result.lastIndex || 0),
      explicitIndex: !!result.explicitIndex,
      sampleKind: String(result.sampleKind || ''),
      samples: Array.isArray(result.samples) ? result.samples : []
    });
  }
  return {
    scheme: publicImportScheme(scheme),
    pythonVersion: runtime.version,
    updates
  };
}

function safeUploadedImportName(fileName) {
  const baseName = path.basename(String(fileName || 'waveform-data.txt'))
    .replace(/[\u0000-\u001f<>:"/\\|?*]/g, '_')
    .slice(0, 180);
  return baseName && baseName !== '.' && baseName !== '..'
    ? baseName
    : 'waveform-data.txt';
}

function normalizeImportedSignalName(value) {
  const signalName = String(value || '').trim();
  if (!signalName) throw new Error('Signal name is required');
  if (signalName.length > 256 || /[\u0000-\u001f]/.test(signalName)) {
    throw new Error('Signal name is invalid');
  }
  return signalName;
}

async function runUploadedImport(options, fileBuffer) {
  const runtime = getPythonRuntimeInfo();
  if (!runtime.available) throw new Error(runtime.error);
  if (!Buffer.isBuffer(fileBuffer) || fileBuffer.length === 0) {
    throw new Error('Uploaded waveform data file is empty');
  }
  const scheme = loadImportScheme(options && options.schemeId);
  const mappingIndex = Number(options && options.mappingIndex);
  if (!Number.isInteger(mappingIndex)
      || mappingIndex < 0
      || mappingIndex >= scheme.mappings.length) {
    throw new Error('Invalid import scheme mapping');
  }
  const signalName = normalizeImportedSignalName(options && options.signalName);
  const uploadedFileName = safeUploadedImportName(options && options.fileName);
  const temporaryDirectory = fs.mkdtempSync(path.join(os.tmpdir(), 'visualwavedrom-import-'));
  const temporaryFilePath = path.join(temporaryDirectory, uploadedFileName);
  try {
    fs.writeFileSync(temporaryFilePath, fileBuffer);
    const sourceMapping = scheme.mappings[mappingIndex];
    const sampleText = fileBuffer.subarray(0, Math.min(fileBuffer.length, 64 * 1024))
      .toString('utf8');
    const analysis = analyzeImportSample(
      uploadedFileName,
      sampleText.split(/\r?\n/).slice(0, importSampleLineLimit)
    );
    const effectiveOptions = Object.assign({}, sourceMapping.options);
    if (analysis.headerLikely
        && !Object.prototype.hasOwnProperty.call(effectiveOptions, 'skipRows')) {
      effectiveOptions.skipRows = 1;
    }
    const result = await runImportParser(Object.assign({}, sourceMapping, {
      sourcePath: temporaryFilePath,
      displayPath: uploadedFileName,
      options: effectiveOptions
    }), runtime);
    return {
      scheme: publicImportScheme(scheme),
      mappingIndex,
      parser: sourceMapping.parser,
      pythonVersion: runtime.version,
      analysis,
      updates: [{
        signal: signalName,
        wave: result.wave,
        data: result.data,
        sourceFile: uploadedFileName,
        parser: sourceMapping.parser,
        pointCount: Number(result.pointCount || 0),
        firstIndex: Number(result.firstIndex || 0),
        lastIndex: Number(result.lastIndex || 0),
        explicitIndex: !!result.explicitIndex,
        sampleKind: String(result.sampleKind || ''),
        samples: Array.isArray(result.samples) ? result.samples : [],
        createIfMissing: true
      }]
    };
  } finally {
    try {
      fs.rmSync(temporaryDirectory, { recursive: true, force: true });
    } catch (_error) {
      // Temporary upload cleanup is best effort.
    }
  }
}

function serveStatic(req, res, pathname) {
  const relative = pathname === '/' ? htmlName : decodeURIComponent(pathname).replace(/^\/+/, '');
  const target = path.resolve(rootDir, relative);
  if (!pathIsInsideRoot(rootDir, target) || !fs.existsSync(target) || fs.statSync(target).isDirectory()) {
    res.writeHead(404); res.end('Not found'); return;
  }
  const realTarget = fs.realpathSync(target);
  if (!pathIsInsideRoot(rootRealDir, realTarget)) {
    res.writeHead(404); res.end('Not found'); return;
  }
  res.writeHead(200, { 'Content-Type': contentType(realTarget) });
  fs.createReadStream(realTarget).pipe(res);
}

function resolveRequestLibraryPath(url, useConfiguredDefault) {
  const byId = libraryPathById(url.searchParams.get('libraryId'));
  if (byId) return byId;
  const fileName = url.searchParams.get('file');
  if (fileName) return safeLibraryPath(fileName);
  return useConfiguredDefault ? configuredLibraryPath : null;
}

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, `http://${req.headers.host || '127.0.0.1'}`);
  try {
    if (url.pathname === '/open' && req.method === 'GET') {
      const target = new URL(`/${htmlName}`, `http://${req.headers.host || '127.0.0.1'}`);
      url.searchParams.forEach((value, name) => target.searchParams.set(name, value));
      res.writeHead(302, { Location: `${target.pathname}${target.search}` });
      res.end();
      return;
    }
    if (url.pathname === '/api/server-info' && req.method === 'GET') {
      const library = sqliteStore.readLibrarySummary(configuredLibraryPath);
      sendJson(res, 200, {
        app: appId,
        rootDir,
        htmlName,
        platform: process.platform,
        nodeVersion: process.versions.node,
        sqliteVersion: sqliteRuntimeInfo && sqliteRuntimeInfo.version,
        protocolScheme: activeProtocolScheme,
        libraryDir: waveDir,
        currentLibrary: configuredLibraryName,
        currentLibraryId: library.libraryId
      });
      return;
    }
    if (url.pathname === '/api/client-connect' && req.method === 'POST') {
      const clientId = url.searchParams.get('id') || 'anonymous-client';
      connectedClients.add(clientId);
      clearTimeout(shutdownTimer);
      shutdownTimer = null;
      sendJson(res, 200, { ok: true, clients: connectedClients.size });
      return;
    }
    if (url.pathname === '/api/client-disconnect' && req.method === 'POST') {
      const clientId = url.searchParams.get('id') || 'anonymous-client';
      connectedClients.delete(clientId);
      clearTimeout(shutdownTimer);
      if (connectedClients.size === 0) {
        shutdownTimer = setTimeout(() => {
          server.close(() => process.exit(0));
        }, 1800);
      }
      sendJson(res, 200, { ok: true, clients: connectedClients.size });
      return;
    }
    if (url.pathname === '/api/import-schemes' && req.method === 'GET') {
      const catalog = listImportSchemes();
      const python = getPythonRuntimeInfo();
      sendJson(res, 200, {
        schemes: catalog.schemes,
        invalid: catalog.invalid,
        python: {
          available: python.available,
          version: python.version || '',
          error: python.error || ''
        }
      });
      return;
    }
    if (url.pathname === '/api/import-wave-analyze' && req.method === 'POST') {
      const payload = JSON.parse(await readRequestBody(req, 64 * 1024));
      const python = getPythonRuntimeInfo();
      sendJson(res, 200, Object.assign({
        ok: true,
        python: {
          available: python.available,
          version: python.version || '',
          error: python.error || ''
        }
      }, analyzeImportFileRequest(payload)));
      return;
    }
    if (url.pathname === '/api/import-wave-preview' && req.method === 'POST') {
      const fileBuffer = await readRequestBuffer(req, importMaxUploadBytes);
      const result = await runUploadedImport({
        schemeId: url.searchParams.get('schemeId'),
        mappingIndex: url.searchParams.get('mappingIndex'),
        signalName: url.searchParams.get('signalName'),
        fileName: url.searchParams.get('fileName')
      }, fileBuffer);
      sendJson(res, 200, Object.assign({ ok: true }, result));
      return;
    }
    if (url.pathname === '/api/import-wave-row' && req.method === 'POST') {
      const payload = JSON.parse(await readRequestBody(req, 128 * 1024));
      const result = await runImportScheme(payload && payload.schemeId);
      sendJson(res, 200, Object.assign({ ok: true }, result));
      return;
    }
    if (url.pathname === '/api/wave-libraries' && req.method === 'GET') {
      const libraries = listLibraries();
      const recent = libraries.find((item) => item.name === readRecentLibraryName());
      const configured = libraries.find((item) => item.name === configuredLibraryName);
      const current = recent || configured || libraries[0] || null;
      sendJson(res, 200, {
        files: libraries.map((item) => item.name),
        libraries,
        current: current && current.name,
        currentLibraryId: current && current.libraryId,
        protocolScheme: activeProtocolScheme
      });
      return;
    }
    if (url.pathname === '/api/wave-library') {
      const filePath = resolveRequestLibraryPath(url, true);
      if (!filePath) { sendJson(res, 400, { error: 'Invalid library' }); return; }
      if (req.method === 'GET') {
        if (!fs.existsSync(filePath) || !sqliteStore.isLibraryFile(filePath)) { sendJson(res, 404, { error: 'Library not found' }); return; }
        const summaryOnly = url.searchParams.get('summary') === '1';
        const library = summaryOnly
          ? sqliteStore.readLibrarySummary(filePath)
          : sqliteStore.readLibrary(filePath);
        rememberLibraryName(libraryNameFromPath(filePath));
        sendJson(res, 200, library);
        return;
      }
      if (req.method === 'POST') {
        const incoming = JSON.parse(await readRequestBody(req, maxWaveLibraryRequestBytes));
        if (!incoming || incoming.kind !== libraryKind || !Array.isArray(incoming.documents)) {
          throw new Error('Invalid library');
        }
        const existing = fs.existsSync(filePath) && sqliteStore.isLibraryFile(filePath)
          ? sqliteStore.readLibrary(filePath)
          : null;
        if (!incoming.libraryId && existing) incoming.libraryId = existing.libraryId;
        if (existing && incoming.libraryId !== existing.libraryId) {
          sendJson(res, 409, { error: 'Library identity conflict', libraryId: existing.libraryId });
          return;
        }
        normalizeLibraryIdentity(incoming);
        if (existing) {
          const existingByName = new Map(existing.documents
            .filter((document) => document && typeof document.name === 'string')
            .map((document) => [document.name, document]));
          const conflict = incoming.documents.find((document) => {
            const current = document && existingByName.get(document.name);
            if (!current || document.revision === current.revision) return false;
            const sameState = document.content === current.content
              && document.hscale === current.hscale
              && document.waveEditMode === current.waveEditMode;
            if (sameState) {
              document.revision = current.revision;
              return false;
            }
            return true;
          });
          if (conflict) {
            sendJson(res, 409, {
              error: 'Wave document revision conflict',
              waveId: conflict.name
            });
            return;
          }
        }
        incoming.updatedAt = new Date().toISOString();
        sqliteStore.writeLibrary(filePath, incoming);
        rememberLibraryName(libraryNameFromPath(filePath));
        sendJson(res, 200, {
          ok: true,
          file: path.basename(path.dirname(filePath)),
          libraryId: incoming.libraryId
        });
        return;
      }
    }
    if (url.pathname === '/api/wave-library-state' && req.method === 'PATCH') {
      const payload = JSON.parse(await readRequestBody(req, maxWaveLibraryRequestBytes));
      const libraryId = String(payload.libraryId || '');
      const filePath = libraryPathById(libraryId);
      if (!filePath) { sendJson(res, 404, { error: 'Wave library not found' }); return; }
      const result = sqliteStore.patchLibraryState(filePath, payload);
      if (result.status === 409) {
        sendJson(res, 409, { error: result.error, waveId: result.waveId });
        return;
      }
      sendJson(res, 200, {
        ok: true,
        libraryId,
        file: path.basename(path.dirname(filePath)),
        revisions: result.revisions,
        deletedDocuments: result.deletedDocuments
      });
      return;
    }
    if (url.pathname === '/api/wave-document') {
      if (req.method === 'GET') {
        const filePath = resolveRequestLibraryPath(url, false);
        const waveId = String(url.searchParams.get('waveId') || '');
        if (!filePath || !waveId || !fs.existsSync(filePath)) {
          sendJson(res, 404, { error: 'Wave document not found' });
          return;
        }
        const library = sqliteStore.readLibrarySummary(filePath);
        const document = sqliteStore.readWaveDocument(filePath, waveId);
        if (!document) { sendJson(res, 404, { error: 'Wave document not found' }); return; }
        sendJson(res, 200, {
          libraryId: library.libraryId,
          file: path.basename(path.dirname(filePath)),
          document
        });
        return;
      }
      if (req.method === 'PATCH') {
        const payload = JSON.parse(await readRequestBody(req, maxWaveLibraryRequestBytes));
        const libraryId = String(payload.libraryId || '');
        const waveId = String(payload.waveId || '');
        const filePath = libraryPathById(libraryId);
        if (!filePath || !waveId || !payload.document) {
          sendJson(res, 404, { error: 'Wave document not found' });
          return;
        }
        const result = sqliteStore.updateWaveDocument(filePath, payload);
        if (result.status !== 200) {
          sendJson(res, result.status, { error: result.error, document: result.document });
          return;
        }
        sendJson(res, 200, {
          ok: true,
          libraryId,
          file: path.basename(path.dirname(filePath)),
          document: result.document
        });
        return;
      }
    }
    serveStatic(req, res, url.pathname);
  } catch (error) {
    if (!res.headersSent) sendJson(res, 400, { error: error.message });
    else res.end();
  }
});

if (!fs.existsSync(htmlPath) || !fs.statSync(htmlPath).isFile()) {
  console.error(`HTML file not found: ${htmlPath}`);
  process.exit(1);
}
try {
  sqliteRuntimeInfo = sqliteStore.getRuntimeInfo();
  ensureWaveDirectory();
  registerProtocolHandler(protocolHandlerPath);
} catch (error) {
  console.error(`VisualWaveDrom startup failed: ${error.message}`);
  process.exit(1);
}
server.on('listening', () => {
  const serverAddress = server.address();
  const activePort = serverAddress && typeof serverAddress === 'object' ? serverAddress.port : requestedPort;
  const address = pageAddress(activePort, requestedOpenUrl);
  if (activePort !== preferredPort) {
    console.log(`Port ${preferredPort} is in use; using available port ${activePort}.`);
  }
  console.log(
    `Runtime: ${process.platform} / Node ${process.versions.node}`
    + ` / SQLite ${sqliteRuntimeInfo ? sqliteRuntimeInfo.version : 'unknown'}`
  );
  console.log(`VisualWaveDrom is running at ${address}`);
  openAddress(address);
});

server.on('error', async (error) => {
  if (error.code !== 'EADDRINUSE' || selectingFallbackPort) {
    console.error(`VisualWaveDrom failed to start: ${error.message}`);
    process.exitCode = 1;
    return;
  }

  const occupiedPort = requestedPort;
  const info = await probeServerInfo(occupiedPort);
  const sameService = info
    && info.app === appId
    && info.htmlName === htmlName
    && info.currentLibrary === configuredLibraryName
    && normalizedRoot(info.rootDir) === normalizedRoot(rootDir)
    && normalizedRoot(info.libraryDir) === normalizedRoot(waveDir);

  if (sameService) {
    const address = pageAddress(occupiedPort, requestedOpenUrl);
    console.log(`VisualWaveDrom is already running at ${address}`);
    openAddress(address);
    return;
  }

  selectingFallbackPort = true;
  requestedPort = 0;
  console.log(`Port ${occupiedPort} is already in use; selecting an available port.`);
  server.listen(0, '127.0.0.1');
});

requestedPort = preferredPort;
server.listen(requestedPort, '127.0.0.1');
