package main

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"mime"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
)

const (
	appID                      = "VisualWaveDrom"
	protocolScheme             = "visualwavedrom"
	serviceAPIVersion          = 6
	defaultPort                = 4173
	maxWaveLibraryRequestBytes = 256 * 1024 * 1024
	importMaxUploadBytes       = 128 * 1024 * 1024
	browserLaunchProbeDelay    = 2 * time.Second
	clientHeartbeatInterval    = 15 * time.Second
	clientLeaseTimeout         = 90 * time.Second
	clientShutdownDelay        = 1800 * time.Millisecond
	clientStartupGracePeriod   = 30 * time.Second
	clientTimerMinimumDelay    = 50 * time.Millisecond
)

var buildVersion = "dev"

const defaultWaveDocument = `{
  "signal": [
    {
      "name": "clk",
      "wave": "p.....|",
      "node": ".a....|"
    },
    {
      "name": "dat",
      "wave": "x.345x|=",
      "data": [
        "head",
        "body",
        "tail",
        "data"
      ],
      "node": "....b..."
    },
    {
      "name": "bus",
      "wave": "x.34.5x|......",
      "data": [
        "write",
        "read",
        "data"
      ]
    },
    {
      "name": "wire",
      "wave": "0.1..0.|1.0"
    },
    {
      "name": "err",
      "wave": "x.....|"
    }
  ],
  "edge": [
    "a->b"
  ],
  "head": {
    "text": "WaveDrom Example"
  },
  "foot": {
    "text": "Generated by VisualWaveDrom"
  },
  "config": {
    "hscale": 1
  }
}
`

type stringList []string

func (values *stringList) String() string {
	return strings.Join(*values, ",")
}

func (values *stringList) Set(value string) error {
	*values = append(*values, value)
	return nil
}

type config struct {
	rootDir             string
	htmlName            string
	htmlPath            string
	configuredLibrary   string
	configuredName      string
	waveDir             string
	statePath           string
	protocolHandlerPath string
	openURL             string
	noOpen              bool
	port                int
	checkRuntime        bool
}

type libraryListItem struct {
	Name          string  `json:"name"`
	LibraryID     string  `json:"libraryId"`
	DocumentCount int     `json:"documentCount"`
	MtimeMS       float64 `json:"mtimeMs"`
}

type service struct {
	config        config
	store         *sqliteStore
	imports       *importManager
	sqliteVersion string
	activeScheme  string
	httpServer    *http.Server
	clientMu      sync.Mutex
	clients       map[string]clientLease
	shutdownTimer *time.Timer
	stateMu       sync.Mutex
}

type clientLease struct {
	token    string
	lastSeen time.Time
}

func stableID(prefix string) string {
	data := make([]byte, 16)
	if _, err := rand.Read(data); err != nil {
		return fmt.Sprintf("%s-%d", prefix, time.Now().UnixNano())
	}
	data[6] = (data[6] & 0x0f) | 0x40
	data[8] = (data[8] & 0x3f) | 0x80
	encoded := hex.EncodeToString(data)
	return fmt.Sprintf("%s-%s-%s-%s-%s-%s", prefix, encoded[:8], encoded[8:12],
		encoded[12:16], encoded[16:20], encoded[20:])
}

func defaultRootDir() string {
	executable, err := os.Executable()
	if err == nil {
		executable, _ = filepath.Abs(executable)
		directory := filepath.Dir(executable)
		if strings.EqualFold(filepath.Base(directory), "bin") {
			parent := filepath.Dir(directory)
			if _, statErr := os.Stat(filepath.Join(parent, "VisualWaveDrom.html")); statErr == nil {
				return parent
			}
		}
	}
	if current, err := os.Getwd(); err == nil {
		return current
	}
	return "."
}

func parseConfig() (config, error) {
	var root, html, library, protocolHandler, openURL string
	var noOpen, checkRuntime bool
	flag.StringVar(&root, "root", "", "project root directory")
	flag.StringVar(&html, "html", "VisualWaveDrom.html", "HTML file name")
	flag.StringVar(&library, "library", "Wave/VisualWaveDrom-library/library.sqlite", "wave library path")
	flag.StringVar(&protocolHandler, "protocol-handler", "", "BAT or SH protocol launcher")
	flag.StringVar(&openURL, "open-url", "", "VisualWaveDrom URL to open")
	flag.BoolVar(&noOpen, "no-open", false, "do not open a browser")
	flag.BoolVar(&checkRuntime, "check-runtime", false, "print runtime information and exit")
	flag.Parse()

	if root == "" {
		root = defaultRootDir()
	}
	root, err := filepath.Abs(root)
	if err != nil {
		return config{}, err
	}
	root = filepath.Clean(root)
	if filepath.Base(html) != html || !(strings.HasSuffix(strings.ToLower(html), ".html") ||
		strings.HasSuffix(strings.ToLower(html), ".htm")) {
		return config{}, fmt.Errorf("invalid HTML file name: %s", html)
	}
	htmlPath := filepath.Join(root, html)
	libraryPath := library
	if !filepath.IsAbs(libraryPath) {
		libraryPath = filepath.Join(root, libraryPath)
	}
	libraryPath, err = filepath.Abs(libraryPath)
	if err != nil {
		return config{}, err
	}
	if !strings.EqualFold(filepath.Ext(libraryPath), ".sqlite") {
		return config{}, fmt.Errorf("wave library must be a .sqlite file: %s", library)
	}
	isFolderDatabase := strings.EqualFold(filepath.Base(libraryPath), "library.sqlite")
	libraryDirectory := filepath.Dir(libraryPath)
	waveDir := filepath.Dir(libraryPath)
	configuredName := strings.TrimSuffix(filepath.Base(libraryPath), filepath.Ext(libraryPath))
	if isFolderDatabase {
		waveDir = filepath.Dir(libraryDirectory)
		configuredName = filepath.Base(libraryDirectory)
	}
	port := defaultPort
	if configuredPort, err := strconv.Atoi(os.Getenv("PORT")); err == nil &&
		configuredPort >= 1 && configuredPort <= 65535 {
		port = configuredPort
	}
	if protocolHandler != "" && !filepath.IsAbs(protocolHandler) {
		protocolHandler = filepath.Join(root, protocolHandler)
	}
	return config{
		rootDir: root, htmlName: html, htmlPath: htmlPath,
		configuredLibrary: libraryPath, configuredName: configuredName,
		waveDir: waveDir, statePath: filepath.Join(waveDir, ".visualwavedrom-state.json"),
		protocolHandlerPath: protocolHandler, openURL: openURL, noOpen: noOpen,
		port: port, checkRuntime: checkRuntime,
	}, nil
}

func newService(configuration config) (*service, error) {
	info, err := os.Stat(configuration.htmlPath)
	if err != nil || info.IsDir() {
		return nil, fmt.Errorf("HTML file not found: %s", configuration.htmlPath)
	}
	store := newSQLiteStore()
	sqliteVersion, err := store.runtimeVersion()
	if err != nil {
		return nil, fmt.Errorf("SQLite startup failed: %w", err)
	}
	instance := &service{
		config: configuration, store: store, imports: newImportManager(configuration.rootDir),
		sqliteVersion: sqliteVersion, activeScheme: protocolScheme,
		clients: make(map[string]clientLease),
	}
	if err = instance.ensureWaveDirectory(); err != nil {
		return nil, err
	}
	instance.refreshActiveScheme()
	return instance, nil
}

func (s *service) ensureWaveDirectory() error {
	if err := os.MkdirAll(s.config.waveDir, 0o755); err != nil {
		return err
	}
	if _, err := os.Stat(s.config.configuredLibrary); err == nil {
		if !s.store.isLibraryFile(s.config.configuredLibrary) {
			return fmt.Errorf("invalid SQLite wave library: %s", s.config.configuredLibrary)
		}
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	library := waveLibrary{
		Kind: libraryKind, Version: 2, LibraryID: stableID("library"),
		UpdatedAt: isoNow(), Directories: []any{}, RootDocuments: []any{},
		ActiveDocumentName: "default-wave", SelectedDirectoryID: "nav-root",
		Documents: []map[string]any{{
			"name": "default-wave", "content": defaultWaveDocument, "hscale": 1,
			"waveEditMode": "modify", "revision": 0, "savedAt": isoNow(),
		}},
	}
	return s.store.writeLibrary(s.config.configuredLibrary, library)
}

func (s *service) readRecentLibraryName() string {
	s.stateMu.Lock()
	defer s.stateMu.Unlock()
	data, err := os.ReadFile(s.config.statePath)
	if err != nil {
		return ""
	}
	var state map[string]any
	if json.Unmarshal(data, &state) != nil {
		return ""
	}
	name := stringValue(state["recentLibrary"])
	if name == "" || filepath.Base(name) != name {
		return ""
	}
	return name
}

func writeJSONAtomically(filePath string, value any) error {
	if err := os.MkdirAll(filepath.Dir(filePath), 0o755); err != nil {
		return err
	}
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	tempFile, err := os.CreateTemp(filepath.Dir(filePath), filepath.Base(filePath)+".*.tmp")
	if err != nil {
		return err
	}
	tempName := tempFile.Name()
	defer os.Remove(tempName)
	if _, err = tempFile.Write(data); err == nil {
		err = tempFile.Sync()
	}
	if closeErr := tempFile.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return err
	}
	if runtime.GOOS == "windows" {
		_ = os.Remove(filePath)
	}
	return os.Rename(tempName, filePath)
}

func (s *service) rememberLibraryName(name string) {
	if name == "" || filepath.Base(name) != name {
		return
	}
	s.stateMu.Lock()
	defer s.stateMu.Unlock()
	_ = writeJSONAtomically(s.config.statePath, map[string]any{
		"version": 1, "recentLibrary": name, "updatedAt": isoNow(),
	})
}

func (s *service) libraryNameFromPath(filePath string) string {
	if samePath(filePath, s.config.configuredLibrary) {
		return s.config.configuredName
	}
	if strings.EqualFold(filepath.Base(filePath), "library.sqlite") {
		return filepath.Base(filepath.Dir(filePath))
	}
	return strings.TrimSuffix(filepath.Base(filePath), filepath.Ext(filePath))
}

func (s *service) listLibraries() []libraryListItem {
	_ = s.ensureWaveDirectory()
	libraries := make([]libraryListItem, 0)
	seen := make(map[string]bool)
	entries, _ := os.ReadDir(s.config.waveDir)
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		filePath := filepath.Join(s.config.waveDir, entry.Name(), "library.sqlite")
		if !s.store.isLibraryFile(filePath) {
			continue
		}
		info, err := s.store.getLibraryInfo(filePath)
		stat, statErr := os.Stat(filePath)
		if err != nil || statErr != nil {
			continue
		}
		libraries = append(libraries, libraryListItem{
			Name: entry.Name(), LibraryID: info.LibraryID,
			DocumentCount: info.DocumentCount, MtimeMS: float64(stat.ModTime().UnixNano()) / 1e6,
		})
		seen[entry.Name()] = true
	}
	if !seen[s.config.configuredName] && s.store.isLibraryFile(s.config.configuredLibrary) {
		if info, err := s.store.getLibraryInfo(s.config.configuredLibrary); err == nil {
			if stat, statErr := os.Stat(s.config.configuredLibrary); statErr == nil {
				libraries = append(libraries, libraryListItem{
					Name: s.config.configuredName, LibraryID: info.LibraryID,
					DocumentCount: info.DocumentCount,
					MtimeMS:       float64(stat.ModTime().UnixNano()) / 1e6,
				})
			}
		}
	}
	sort.Slice(libraries, func(i, j int) bool { return libraries[i].MtimeMS > libraries[j].MtimeMS })
	return libraries
}

func containsControl(text string) bool {
	return strings.IndexFunc(text, func(character rune) bool { return character < 0x20 }) >= 0
}

func (s *service) safeLibraryPath(name string) string {
	requested := strings.TrimSpace(name)
	if requested == "" || filepath.Base(requested) != requested ||
		requested == "." || requested == ".." || strings.ContainsAny(requested, `/\`) ||
		containsControl(requested) {
		return ""
	}
	if requested == s.config.configuredName {
		return s.config.configuredLibrary
	}
	return filepath.Join(s.config.waveDir, requested, "library.sqlite")
}

func (s *service) libraryPathByID(id string) string {
	id = strings.TrimSpace(id)
	if id == "" {
		return ""
	}
	for _, library := range s.listLibraries() {
		if library.LibraryID == id {
			return s.safeLibraryPath(library.Name)
		}
	}
	return ""
}

func samePath(left, right string) bool {
	left, _ = filepath.Abs(left)
	right, _ = filepath.Abs(right)
	if runtime.GOOS == "windows" {
		return strings.EqualFold(left, right)
	}
	return left == right
}

func canonicalExistingPath(value string) string {
	resolved, err := filepath.EvalSymlinks(value)
	if err == nil {
		return resolved
	}
	absolute, absoluteErr := filepath.Abs(value)
	if absoluteErr == nil {
		return filepath.Clean(absolute)
	}
	return filepath.Clean(value)
}

func (s *service) refreshActiveScheme() {
	library, err := s.store.readLibrary(s.config.configuredLibrary, true)
	if err != nil {
		return
	}
	suffixBuilder := strings.Builder{}
	for _, character := range strings.ToLower(library.LibraryID) {
		if (character >= 'a' && character <= 'z') || (character >= '0' && character <= '9') ||
			character == '+' || character == '.' || character == '-' {
			suffixBuilder.WriteRune(character)
		} else {
			suffixBuilder.WriteRune('-')
		}
	}
	if suffix := suffixBuilder.String(); suffix != "" {
		s.activeScheme = protocolScheme + "-" + suffix
	}
}

func (s *service) registerProtocolHandler() {
	handler := s.config.protocolHandlerPath
	if handler == "" {
		return
	}
	handler, _ = filepath.Abs(handler)
	info, err := os.Stat(handler)
	if err != nil || info.IsDir() {
		log.Printf("Protocol handler not found: %s", handler)
		return
	}
	if runtime.GOOS == "windows" {
		s.registerWindowsProtocol(handler)
	} else if runtime.GOOS == "linux" {
		s.registerLinuxProtocol(handler)
	}
}

func (s *service) registerWindowsProtocol(handler string) {
	if !strings.EqualFold(filepath.Ext(handler), ".bat") || strings.Contains(handler, `"`) {
		log.Printf("Protocol handler BAT not found: %s", handler)
		return
	}
	command := fmt.Sprintf(`"%s" "%%1"`, handler)
	schemes := []string{s.activeScheme}
	if s.activeScheme != protocolScheme {
		schemes = append(schemes, protocolScheme)
	}
	for _, scheme := range schemes {
		key := `HKCU\Software\Classes\` + scheme
		commands := [][]string{
			{"add", key, "/ve", "/d", "URL:VisualWaveDrom Protocol", "/f"},
			{"add", key, "/v", "URL Protocol", "/t", "REG_SZ", "/f"},
			{"add", key + `\DefaultIcon`, "/ve", "/d", `"` + s.config.htmlPath + `",0`, "/f"},
			{"add", key + `\shell\open\command`, "/ve", "/d", command, "/f"},
		}
		for _, arguments := range commands {
			run := exec.Command("reg.exe", arguments...)
			run.Stdout = nil
			run.Stderr = nil
			if err := run.Run(); err != nil {
				log.Printf("Could not register the VisualWaveDrom URL protocol: %v", err)
				return
			}
		}
	}
}

func desktopQuoted(value string) string {
	replacer := strings.NewReplacer(`\`, `\\\\`, `"`, `\"`, "`", "\\`", "$", `\$`, "%", "%%")
	return `"` + replacer.Replace(value) + `"`
}

func (s *service) registerLinuxProtocol(handler string) {
	if filepath.Ext(handler) != ".sh" || strings.ContainsAny(handler, "\x00\r\n") {
		log.Printf("Protocol handler shell script not found: %s", handler)
		return
	}
	home, err := os.UserHomeDir()
	if err != nil || !filepath.IsAbs(home) {
		log.Print("Could not register the VisualWaveDrom URL protocol: HOME is not set.")
		return
	}
	dataHome := os.Getenv("XDG_DATA_HOME")
	if !filepath.IsAbs(dataHome) {
		dataHome = filepath.Join(home, ".local", "share")
	}
	applications := filepath.Join(dataHome, "applications")
	if err = os.MkdirAll(applications, 0o755); err != nil {
		log.Printf("Could not create desktop application directory: %v", err)
		return
	}
	fileName := strings.Map(func(character rune) rune {
		if (character >= 'a' && character <= 'z') || (character >= '0' && character <= '9') ||
			character == '+' || character == '.' || character == '-' {
			return character
		}
		return '-'
	}, s.activeScheme) + ".desktop"
	schemes := []string{s.activeScheme}
	if s.activeScheme != protocolScheme {
		schemes = append(schemes, protocolScheme)
	}
	mimeTypes := strings.Builder{}
	for _, scheme := range schemes {
		mimeTypes.WriteString("x-scheme-handler/" + scheme + ";")
	}
	displayName := strings.NewReplacer("\r", " ", "\n", " ", "\t", " ").Replace(s.config.configuredName)
	entry := "[Desktop Entry]\nVersion=1.0\nType=Application\n" +
		"Name=VisualWaveDrom - " + displayName + "\n" +
		"Exec=bash " + desktopQuoted(handler) + " %u\n" +
		"Terminal=true\nNoDisplay=true\nStartupNotify=false\n" +
		"Categories=Development;Utility;\nMimeType=" + mimeTypes.String() + "\n"
	desktopPath := filepath.Join(applications, fileName)
	if err = os.WriteFile(desktopPath, []byte(entry), 0o644); err != nil {
		log.Printf("Could not write desktop entry: %v", err)
		return
	}
	if os.Getenv("DISPLAY") == "" && os.Getenv("WAYLAND_DISPLAY") == "" {
		log.Print("Linux URL protocol registration will finish on the next desktop-session launch.")
		return
	}
	_ = exec.Command("update-desktop-database", applications).Run()
	for _, scheme := range schemes {
		if err = exec.Command("xdg-mime", "default", fileName, "x-scheme-handler/"+scheme).Run(); err != nil {
			log.Printf("Could not register URL protocol with xdg-mime: %v", err)
		}
	}
}

func (s *service) requestedPagePath(rawURL string) string {
	if rawURL == "" {
		return "/" + url.PathEscape(s.config.htmlName)
	}
	parsed, err := url.Parse(rawURL)
	if err != nil || (parsed.Scheme != protocolScheme && parsed.Scheme != s.activeScheme) {
		return "/" + url.PathEscape(s.config.htmlName)
	}
	query := url.Values{}
	for _, name := range []string{"libraryId", "waveId", "view"} {
		if value := parsed.Query().Get(name); value != "" {
			query.Set(name, value)
		}
	}
	if query.Get("view") == "" {
		query.Set("view", "single")
	}
	return "/open?" + query.Encode()
}

func (s *service) pageAddress(port int) string {
	pagePath := s.requestedPagePath(s.config.openURL)
	separator := "?"
	if strings.Contains(pagePath, "?") {
		separator = "&"
	}
	pagePath += separator + "serviceApi=" + strconv.Itoa(serviceAPIVersion)
	return fmt.Sprintf("http://127.0.0.1:%d%s", port, pagePath)
}

func browserCommands(goos, address string) [][]string {
	switch goos {
	case "windows":
		return [][]string{{"rundll32.exe", "url.dll,FileProtocolHandler", address}}
	case "darwin":
		return [][]string{{"open", address}}
	default:
		return [][]string{
			{"xdg-open", address},
			{"gio", "open", address},
			{"sensible-browser", address},
			{"kde-open5", address},
			{"kde-open", address},
			{"gnome-open", address},
		}
	}
}

func launchBrowserCommand(candidate []string, probeDelay time.Duration) error {
	if len(candidate) == 0 {
		return errors.New("empty browser launcher command")
	}
	var stderr strings.Builder
	command := exec.Command(candidate[0], candidate[1:]...)
	command.Stdout = io.Discard
	command.Stderr = &stderr
	if err := command.Start(); err != nil {
		return err
	}
	finished := make(chan error, 1)
	go func() {
		finished <- command.Wait()
	}()
	timer := time.NewTimer(probeDelay)
	defer timer.Stop()
	select {
	case err := <-finished:
		if err == nil {
			return nil
		}
		detail := strings.TrimSpace(stderr.String())
		if detail != "" {
			return fmt.Errorf("%w: %s", err, detail)
		}
		return err
	case <-timer.C:
		// Some launchers remain attached while the browser is open.
		return nil
	}
}

func openBrowser(address string, noOpen bool) {
	if noOpen {
		return
	}
	parsed, err := url.Parse(address)
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") ||
		parsed.Hostname() != "127.0.0.1" {
		log.Printf("Could not open browser automatically: invalid local address")
		return
	}
	failures := make([]string, 0)
	for _, candidate := range browserCommands(runtime.GOOS, address) {
		if err = launchBrowserCommand(candidate, browserLaunchProbeDelay); err == nil {
			return
		}
		failures = append(failures, candidate[0]+": "+err.Error())
	}
	if runtime.GOOS == "linux" && os.Getenv("DISPLAY") == "" && os.Getenv("WAYLAND_DISPLAY") == "" {
		log.Print("Linux desktop variables were not detected, but available browser launchers were tried.")
	}
	log.Printf("Could not open the browser automatically (%s); open the printed URL manually.",
		strings.Join(failures, "; "))
}

func sendJSON(writer http.ResponseWriter, status int, payload any) {
	writer.Header().Set("Content-Type", "application/json; charset=utf-8")
	writer.Header().Set("X-Content-Type-Options", "nosniff")
	writer.WriteHeader(status)
	_ = json.NewEncoder(writer).Encode(payload)
}

func decodeJSONBody(writer http.ResponseWriter, request *http.Request, maxBytes int64, target any) error {
	request.Body = http.MaxBytesReader(writer, request.Body, maxBytes)
	decoder := json.NewDecoder(request.Body)
	decoder.UseNumber()
	if err := decoder.Decode(target); err != nil {
		return err
	}
	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		if err == nil {
			return errors.New("request body contains multiple JSON values")
		}
		return err
	}
	return nil
}

func (s *service) resolveRequestLibrary(requestURL *url.URL, configuredDefault bool) string {
	if byID := s.libraryPathByID(requestURL.Query().Get("libraryId")); byID != "" {
		return byID
	}
	if fileName := requestURL.Query().Get("file"); fileName != "" {
		return s.safeLibraryPath(fileName)
	}
	if configuredDefault {
		return s.config.configuredLibrary
	}
	return ""
}

func (s *service) handleServerInfo(writer http.ResponseWriter, _ *http.Request) {
	library, err := s.store.readLibrary(s.config.configuredLibrary, true)
	if err != nil {
		sendJSON(writer, 500, map[string]any{"error": err.Error()})
		return
	}
	sendJSON(writer, 200, map[string]any{
		"app": appID, "rootDir": s.config.rootDir, "htmlName": s.config.htmlName,
		"platform": runtime.GOOS, "architecture": runtime.GOARCH,
		"runtime": runtime.Version(), "serverVersion": buildVersion,
		"serviceAPIVersion": serviceAPIVersion,
		"sqliteVersion":     s.sqliteVersion, "protocolScheme": s.activeScheme,
		"libraryDir": s.config.waveDir, "currentLibrary": s.config.configuredName,
		"currentLibraryId": library.LibraryID,
	})
}

func requestClientID(request *http.Request) string {
	id := strings.TrimSpace(request.URL.Query().Get("id"))
	if id == "" {
		return "anonymous-client"
	}
	return id
}

func (s *service) stopClientTimerLocked() {
	if s.shutdownTimer == nil {
		return
	}
	s.shutdownTimer.Stop()
	s.shutdownTimer = nil
}

func (s *service) pruneExpiredClientsLocked(now time.Time) {
	for id, lease := range s.clients {
		if now.Sub(lease.lastSeen) >= clientLeaseTimeout {
			delete(s.clients, id)
		}
	}
}

func (s *service) scheduleClientShutdownLocked(delay time.Duration) {
	s.stopClientTimerLocked()
	if delay < clientTimerMinimumDelay {
		delay = clientTimerMinimumDelay
	}
	s.shutdownTimer = time.AfterFunc(delay, s.shutdownIfNoClients)
}

func (s *service) scheduleClientLeaseCheckLocked(now time.Time) {
	s.stopClientTimerLocked()
	if len(s.clients) == 0 {
		s.scheduleClientShutdownLocked(clientShutdownDelay)
		return
	}
	delay := clientLeaseTimeout
	for _, lease := range s.clients {
		remaining := clientLeaseTimeout - now.Sub(lease.lastSeen)
		if remaining < delay {
			delay = remaining
		}
	}
	if delay < clientTimerMinimumDelay {
		delay = clientTimerMinimumDelay
	}
	s.shutdownTimer = time.AfterFunc(delay, s.reapExpiredClients)
}

func (s *service) reapExpiredClients() {
	s.clientMu.Lock()
	s.shutdownTimer = nil
	now := time.Now()
	s.pruneExpiredClientsLocked(now)
	if len(s.clients) == 0 {
		s.scheduleClientShutdownLocked(clientShutdownDelay)
	} else {
		s.scheduleClientLeaseCheckLocked(now)
	}
	s.clientMu.Unlock()
}

func (s *service) shutdownIfNoClients() {
	s.clientMu.Lock()
	s.shutdownTimer = nil
	now := time.Now()
	s.pruneExpiredClientsLocked(now)
	if len(s.clients) != 0 {
		s.scheduleClientLeaseCheckLocked(now)
		s.clientMu.Unlock()
		return
	}
	server := s.httpServer
	s.clientMu.Unlock()
	if server == nil {
		return
	}
	context, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	_ = server.Shutdown(context)
}

func (s *service) touchClient(id, token string) int {
	now := time.Now()
	s.clientMu.Lock()
	s.pruneExpiredClientsLocked(now)
	s.clients[id] = clientLease{token: token, lastSeen: now}
	s.scheduleClientLeaseCheckLocked(now)
	count := len(s.clients)
	s.clientMu.Unlock()
	return count
}

func (s *service) removeClient(id, token string, force bool) int {
	now := time.Now()
	s.clientMu.Lock()
	s.pruneExpiredClientsLocked(now)
	if lease, found := s.clients[id]; found && (force || lease.token == token) {
		delete(s.clients, id)
	}
	if len(s.clients) == 0 {
		s.scheduleClientShutdownLocked(clientShutdownDelay)
	} else {
		s.scheduleClientLeaseCheckLocked(now)
	}
	count := len(s.clients)
	s.clientMu.Unlock()
	return count
}

func (s *service) handleClientConnect(writer http.ResponseWriter, request *http.Request) {
	count := s.touchClient(requestClientID(request), "heartbeat")
	sendJSON(writer, 200, map[string]any{"ok": true, "clients": count})
}

func (s *service) handleClientDisconnect(writer http.ResponseWriter, request *http.Request) {
	count := s.removeClient(requestClientID(request), "", true)
	sendJSON(writer, 200, map[string]any{"ok": true, "clients": count})
}

func (s *service) handleClientSession(writer http.ResponseWriter, request *http.Request) {
	flusher, ok := writer.(http.Flusher)
	if !ok {
		sendJSON(writer, 500, map[string]any{"error": "Streaming is not supported"})
		return
	}
	id := requestClientID(request)
	token := stableID("session")
	s.touchClient(id, token)
	defer s.removeClient(id, token, false)

	writer.Header().Set("Content-Type", "text/event-stream; charset=utf-8")
	writer.Header().Set("Cache-Control", "no-cache, no-store, must-revalidate")
	writer.Header().Set("Connection", "keep-alive")
	writer.Header().Set("X-Accel-Buffering", "no")
	if _, err := fmt.Fprintf(writer, "retry: 3000\nevent: connected\ndata: ok\n\n"); err != nil {
		return
	}
	flusher.Flush()

	ticker := time.NewTicker(clientHeartbeatInterval)
	defer ticker.Stop()
	for {
		select {
		case <-request.Context().Done():
			return
		case <-ticker.C:
			s.clientMu.Lock()
			lease, active := s.clients[id]
			if active && lease.token == token {
				lease.lastSeen = time.Now()
				s.clients[id] = lease
				s.scheduleClientLeaseCheckLocked(lease.lastSeen)
			}
			s.clientMu.Unlock()
			if !active {
				return
			}
			if _, err := fmt.Fprint(writer, ": keepalive\n\n"); err != nil {
				return
			}
			flusher.Flush()
		}
	}
}

func (s *service) handleImportSchemes(writer http.ResponseWriter, _ *http.Request) {
	catalog := s.imports.listSchemes()
	sendJSON(writer, 200, map[string]any{
		"schemes": catalog.Schemes, "invalid": catalog.Invalid,
		"python": s.imports.pythonRuntime(),
	})
}

func (s *service) handleImportAnalyze(writer http.ResponseWriter, request *http.Request) {
	payload := make(map[string]any)
	if err := decodeJSONBody(writer, request, 64*1024, &payload); err != nil {
		sendJSON(writer, 400, map[string]any{"error": err.Error()})
		return
	}
	var sourceFile map[string]any
	if _, supplied := payload["sourcePath"]; supplied {
		sourcePath, info, err := resolvePastedImportPath(
			stringValue(payload["sourcePath"]), s.config.rootDir)
		if err != nil {
			sendJSON(writer, 400, map[string]any{"error": err.Error()})
			return
		}
		sampleLines, err := readImportSampleLines(sourcePath)
		if err != nil {
			sendJSON(writer, 400, map[string]any{"error": err.Error()})
			return
		}
		payload["fileName"] = info.Name()
		payload["sampleLines"] = sampleLines
		sourceFile = map[string]any{
			"name": info.Name(), "path": sourcePath, "size": info.Size(),
			"modifiedAt": info.ModTime().UTC().Format(time.RFC3339Nano),
		}
	}
	result := s.imports.analyzeRequest(payload)
	result["ok"] = true
	result["python"] = s.imports.pythonRuntime()
	if sourceFile != nil {
		result["sourceFile"] = sourceFile
		result["sampleLines"] = payload["sampleLines"]
	}
	sendJSON(writer, 200, result)
}

func (s *service) handleImportPreview(writer http.ResponseWriter, request *http.Request) {
	if strings.HasPrefix(strings.ToLower(request.Header.Get("Content-Type")), "application/json") {
		payload := make(map[string]any)
		if err := decodeJSONBody(writer, request, 128*1024, &payload); err != nil {
			sendJSON(writer, 400, map[string]any{"error": err.Error()})
			return
		}
		sourcePath, _, err := resolvePastedImportPath(
			stringValue(payload["sourcePath"]), s.config.rootDir)
		if err != nil {
			sendJSON(writer, 400, map[string]any{"error": err.Error()})
			return
		}
		result, err := s.imports.runLocalFile(
			stringValue(payload["schemeId"]),
			intValue(payload["mappingIndex"], -1),
			stringValue(payload["signalName"]),
			sourcePath,
			boolValue(payload["hasIndex"], false),
		)
		if err != nil {
			sendJSON(writer, 400, map[string]any{"error": err.Error()})
			return
		}
		result["ok"] = true
		result["sourcePath"] = sourcePath
		sendJSON(writer, 200, result)
		return
	}
	request.Body = http.MaxBytesReader(writer, request.Body, importMaxUploadBytes)
	data, err := io.ReadAll(request.Body)
	if err != nil {
		sendJSON(writer, 400, map[string]any{"error": err.Error()})
		return
	}
	mappingIndex, _ := strconv.Atoi(request.URL.Query().Get("mappingIndex"))
	result, err := s.imports.runUploaded(
		request.URL.Query().Get("schemeId"), mappingIndex,
		request.URL.Query().Get("signalName"), request.URL.Query().Get("fileName"), data,
		boolValue(request.URL.Query().Get("hasIndex"), false))
	if err != nil {
		sendJSON(writer, 400, map[string]any{"error": err.Error()})
		return
	}
	result["ok"] = true
	sendJSON(writer, 200, result)
}

func (s *service) handleImportRow(writer http.ResponseWriter, request *http.Request) {
	payload := make(map[string]any)
	if err := decodeJSONBody(writer, request, 128*1024, &payload); err != nil {
		sendJSON(writer, 400, map[string]any{"error": err.Error()})
		return
	}
	result, err := s.imports.runScheme(stringValue(payload["schemeId"]))
	if err != nil {
		sendJSON(writer, 400, map[string]any{"error": err.Error()})
		return
	}
	result["ok"] = true
	sendJSON(writer, 200, result)
}

func (s *service) handleLibraries(writer http.ResponseWriter, _ *http.Request) {
	libraries := s.listLibraries()
	currentName := ""
	recent := s.readRecentLibraryName()
	for _, library := range libraries {
		if library.Name == recent {
			currentName = library.Name
			break
		}
	}
	if currentName == "" {
		for _, library := range libraries {
			if library.Name == s.config.configuredName {
				currentName = library.Name
				break
			}
		}
	}
	if currentName == "" && len(libraries) > 0 {
		currentName = libraries[0].Name
	}
	currentID := ""
	for _, library := range libraries {
		if library.Name == currentName {
			currentID = library.LibraryID
		}
	}
	files := make([]string, len(libraries))
	for index, library := range libraries {
		files[index] = library.Name
	}
	sendJSON(writer, 200, map[string]any{
		"files": files, "libraries": libraries, "current": currentName,
		"currentLibraryId": currentID, "protocolScheme": s.activeScheme,
	})
}

func normalizeLibraryIdentity(library *waveLibrary) {
	if library.LibraryID == "" {
		library.LibraryID = stableID("library")
	}
	if library.Version < 2 {
		library.Version = 2
	}
	for _, document := range library.Documents {
		revision := intValue(document["revision"], 0)
		if revision < 0 {
			revision = 0
		}
		document["revision"] = revision
	}
}

func documentsByName(documents []map[string]any) map[string]map[string]any {
	result := make(map[string]map[string]any)
	for _, document := range documents {
		name := stringValue(document["name"])
		if name != "" {
			result[name] = document
		}
	}
	return result
}

func (s *service) handleWaveLibrary(writer http.ResponseWriter, request *http.Request) {
	filePath := s.resolveRequestLibrary(request.URL, true)
	if filePath == "" {
		sendJSON(writer, 400, map[string]any{"error": "Invalid library"})
		return
	}
	switch request.Method {
	case http.MethodGet:
		if !s.store.isLibraryFile(filePath) {
			sendJSON(writer, 404, map[string]any{"error": "Library not found"})
			return
		}
		library, err := s.store.readLibrary(filePath, request.URL.Query().Get("summary") == "1")
		if err != nil {
			sendJSON(writer, 400, map[string]any{"error": err.Error()})
			return
		}
		s.rememberLibraryName(s.libraryNameFromPath(filePath))
		sendJSON(writer, 200, library)
	case http.MethodPost:
		var incoming waveLibrary
		if err := decodeJSONBody(writer, request, maxWaveLibraryRequestBytes, &incoming); err != nil {
			sendJSON(writer, 400, map[string]any{"error": err.Error()})
			return
		}
		if incoming.Kind != libraryKind || incoming.Documents == nil {
			sendJSON(writer, 400, map[string]any{"error": "Invalid library"})
			return
		}
		var existing *waveLibrary
		if s.store.isLibraryFile(filePath) {
			value, err := s.store.readLibrary(filePath, false)
			if err != nil {
				sendJSON(writer, 400, map[string]any{"error": err.Error()})
				return
			}
			existing = &value
		}
		if incoming.LibraryID == "" && existing != nil {
			incoming.LibraryID = existing.LibraryID
		}
		if existing != nil && incoming.LibraryID != existing.LibraryID {
			sendJSON(writer, 409, map[string]any{
				"error": "Library identity conflict", "libraryId": existing.LibraryID,
			})
			return
		}
		normalizeLibraryIdentity(&incoming)
		if existing != nil {
			existingDocuments := documentsByName(existing.Documents)
			for _, document := range incoming.Documents {
				current := existingDocuments[stringValue(document["name"])]
				if current == nil || intValue(document["revision"], 0) == intValue(current["revision"], 0) {
					continue
				}
				if documentsHaveSameState(document, current) {
					document["revision"] = current["revision"]
					continue
				}
				sendJSON(writer, 409, map[string]any{
					"error": "Wave document revision conflict", "waveId": document["name"],
				})
				return
			}
		}
		incoming.UpdatedAt = isoNow()
		if err := s.store.writeLibrary(filePath, incoming); err != nil {
			sendJSON(writer, 400, map[string]any{"error": err.Error()})
			return
		}
		s.rememberLibraryName(s.libraryNameFromPath(filePath))
		sendJSON(writer, 200, map[string]any{
			"ok": true, "file": filepath.Base(filepath.Dir(filePath)),
			"libraryId": incoming.LibraryID,
		})
	default:
		writer.WriteHeader(http.StatusMethodNotAllowed)
	}
}

func (s *service) handleLibraryState(writer http.ResponseWriter, request *http.Request) {
	payload := make(map[string]any)
	if err := decodeJSONBody(writer, request, maxWaveLibraryRequestBytes, &payload); err != nil {
		sendJSON(writer, 400, map[string]any{"error": err.Error()})
		return
	}
	libraryID := stringValue(payload["libraryId"])
	filePath := s.libraryPathByID(libraryID)
	if filePath == "" {
		sendJSON(writer, 404, map[string]any{"error": "Wave library not found"})
		return
	}
	result, err := s.store.patchLibraryState(filePath, payload)
	if err != nil {
		sendJSON(writer, 400, map[string]any{"error": err.Error()})
		return
	}
	if result.Status == 409 {
		sendJSON(writer, 409, map[string]any{"error": result.Error, "waveId": result.WaveID})
		return
	}
	sendJSON(writer, 200, map[string]any{
		"ok": true, "libraryId": libraryID, "file": filepath.Base(filepath.Dir(filePath)),
		"revisions": result.Revisions, "deletedDocuments": result.DeletedDocuments,
	})
}

func (s *service) handleWaveDocument(writer http.ResponseWriter, request *http.Request) {
	switch request.Method {
	case http.MethodGet:
		filePath := s.resolveRequestLibrary(request.URL, false)
		waveID := request.URL.Query().Get("waveId")
		if filePath == "" || waveID == "" || !s.store.isLibraryFile(filePath) {
			sendJSON(writer, 404, map[string]any{"error": "Wave document not found"})
			return
		}
		library, err := s.store.readLibrary(filePath, true)
		if err != nil {
			sendJSON(writer, 400, map[string]any{"error": err.Error()})
			return
		}
		document, err := s.store.readDocument(filePath, waveID)
		if err != nil {
			sendJSON(writer, 400, map[string]any{"error": err.Error()})
			return
		}
		if document == nil {
			sendJSON(writer, 404, map[string]any{"error": "Wave document not found"})
			return
		}
		sendJSON(writer, 200, map[string]any{
			"libraryId": library.LibraryID, "file": filepath.Base(filepath.Dir(filePath)),
			"document": document,
		})
	case http.MethodPatch:
		payload := make(map[string]any)
		if err := decodeJSONBody(writer, request, maxWaveLibraryRequestBytes, &payload); err != nil {
			sendJSON(writer, 400, map[string]any{"error": err.Error()})
			return
		}
		libraryID := stringValue(payload["libraryId"])
		waveID := stringValue(payload["waveId"])
		filePath := s.libraryPathByID(libraryID)
		document, documentOK := payload["document"].(map[string]any)
		if filePath == "" || waveID == "" || !documentOK {
			sendJSON(writer, 404, map[string]any{"error": "Wave document not found"})
			return
		}
		var expectedRevision *int
		if revision, ok := integerValue(payload["expectedRevision"]); ok {
			expectedRevision = &revision
		}
		result, err := s.store.updateDocument(filePath, waveID, expectedRevision, document)
		if err != nil {
			sendJSON(writer, 400, map[string]any{"error": err.Error()})
			return
		}
		if result.Status != 200 {
			sendJSON(writer, result.Status, map[string]any{
				"error": result.Error, "document": result.Document,
			})
			return
		}
		sendJSON(writer, 200, map[string]any{
			"ok": true, "libraryId": libraryID, "file": filepath.Base(filepath.Dir(filePath)),
			"document": result.Document,
		})
	default:
		writer.WriteHeader(http.StatusMethodNotAllowed)
	}
}

func contentType(filePath string) string {
	extension := strings.ToLower(filepath.Ext(filePath))
	if extension == ".js" {
		return "application/javascript; charset=utf-8"
	}
	if extension == ".json" {
		return "application/json; charset=utf-8"
	}
	if extension == ".svg" {
		return "image/svg+xml"
	}
	if extension == ".wasm" {
		return "application/wasm"
	}
	if detected := mime.TypeByExtension(extension); detected != "" {
		return detected
	}
	return "application/octet-stream"
}

func (s *service) serveStatic(writer http.ResponseWriter, request *http.Request) {
	relative := strings.TrimLeft(request.URL.Path, "/")
	if relative == "" {
		relative = s.config.htmlName
	}
	unescaped, err := url.PathUnescape(relative)
	if err != nil {
		http.NotFound(writer, request)
		return
	}
	target, err := filepath.Abs(filepath.Join(s.config.rootDir, filepath.FromSlash(unescaped)))
	if err != nil || !pathInside(s.config.rootDir, target) {
		http.NotFound(writer, request)
		return
	}
	info, err := os.Stat(target)
	if err != nil || info.IsDir() {
		http.NotFound(writer, request)
		return
	}
	realTarget := canonicalExistingPath(target)
	if !pathInside(canonicalExistingPath(s.config.rootDir), realTarget) {
		http.NotFound(writer, request)
		return
	}
	file, err := os.Open(realTarget)
	if err != nil {
		http.NotFound(writer, request)
		return
	}
	defer file.Close()
	writer.Header().Set("Content-Type", contentType(realTarget))
	writer.Header().Set("X-Content-Type-Options", "nosniff")
	switch strings.ToLower(filepath.Ext(realTarget)) {
	case ".html", ".htm":
		writer.Header().Set("Cache-Control", "no-cache, no-store, must-revalidate")
		writer.Header().Set("Pragma", "no-cache")
		writer.Header().Set("Expires", "0")
	case ".js", ".css":
		writer.Header().Set("Cache-Control", "no-cache")
	}
	http.ServeContent(writer, request, info.Name(), info.ModTime(), file)
}

func (s *service) routes() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("/open", func(writer http.ResponseWriter, request *http.Request) {
		if request.Method != http.MethodGet {
			writer.WriteHeader(http.StatusMethodNotAllowed)
			return
		}
		query := request.URL.Query()
		http.Redirect(writer, request, "/"+url.PathEscape(s.config.htmlName)+"?"+query.Encode(),
			http.StatusFound)
	})
	mux.HandleFunc("/api/server-info", method(http.MethodGet, s.handleServerInfo))
	mux.HandleFunc("/api/client-connect", method(http.MethodPost, s.handleClientConnect))
	mux.HandleFunc("/api/client-disconnect", method(http.MethodPost, s.handleClientDisconnect))
	mux.HandleFunc("/api/client-session", method(http.MethodGet, s.handleClientSession))
	mux.HandleFunc("/api/import-schemes", method(http.MethodGet, s.handleImportSchemes))
	mux.HandleFunc("/api/import-wave-analyze", method(http.MethodPost, s.handleImportAnalyze))
	mux.HandleFunc("/api/import-wave-preview", method(http.MethodPost, s.handleImportPreview))
	mux.HandleFunc("/api/import-wave-row", method(http.MethodPost, s.handleImportRow))
	mux.HandleFunc("/api/import-wave-collection", method(http.MethodPost, s.handleImportCollection))
	mux.HandleFunc("/api/wave-libraries", method(http.MethodGet, s.handleLibraries))
	mux.HandleFunc("/api/wave-library", s.handleWaveLibrary)
	mux.HandleFunc("/api/wave-library-state", method(http.MethodPatch, s.handleLibraryState))
	mux.HandleFunc("/api/wave-document", s.handleWaveDocument)
	mux.HandleFunc("/", s.serveStatic)
	return mux
}

func method(expected string, handler http.HandlerFunc) http.HandlerFunc {
	return func(writer http.ResponseWriter, request *http.Request) {
		if request.Method != expected {
			writer.WriteHeader(http.StatusMethodNotAllowed)
			return
		}
		handler(writer, request)
	}
}

func normalizedPath(value string) string {
	resolved, _ := filepath.Abs(value)
	if runtime.GOOS == "windows" {
		return strings.ToLower(resolved)
	}
	return resolved
}

func probeServer(port int) map[string]any {
	client := &http.Client{Timeout: 800 * time.Millisecond}
	response, err := client.Get(fmt.Sprintf("http://127.0.0.1:%d/api/server-info", port))
	if err != nil {
		return nil
	}
	defer response.Body.Close()
	if response.StatusCode != 200 {
		return nil
	}
	reader := io.LimitReader(response.Body, 64*1024)
	var info map[string]any
	if json.NewDecoder(reader).Decode(&info) != nil {
		return nil
	}
	return info
}

func (s *service) sameRunningService(info map[string]any) bool {
	return stringValue(info["app"]) == appID &&
		intValue(info["serviceAPIVersion"], 0) == serviceAPIVersion &&
		stringValue(info["htmlName"]) == s.config.htmlName &&
		stringValue(info["currentLibrary"]) == s.config.configuredName &&
		normalizedPath(stringValue(info["rootDir"])) == normalizedPath(s.config.rootDir) &&
		normalizedPath(stringValue(info["libraryDir"])) == normalizedPath(s.config.waveDir)
}

func listenLocal(port int) (net.Listener, error) {
	return net.Listen("tcp", fmt.Sprintf("127.0.0.1:%d", port))
}

func (s *service) run() error {
	s.registerProtocolHandler()
	listener, err := listenLocal(s.config.port)
	if err != nil {
		if info := probeServer(s.config.port); s.sameRunningService(info) {
			address := s.pageAddress(s.config.port)
			fmt.Printf("VisualWaveDrom is already running at %s\n", address)
			openBrowser(address, s.config.noOpen)
			return nil
		}
		listener, err = listenLocal(0)
		if err != nil {
			return err
		}
		fmt.Printf("Port %d is already in use; using an available port.\n", s.config.port)
	}
	activePort := listener.Addr().(*net.TCPAddr).Port
	address := s.pageAddress(activePort)
	s.httpServer = &http.Server{
		Handler:           s.routes(),
		ReadHeaderTimeout: 10 * time.Second,
		IdleTimeout:       90 * time.Second,
		MaxHeaderBytes:    1 * 1024 * 1024,
	}
	fmt.Printf("Runtime: %s/%s / Go %s / SQLite %s\n",
		runtime.GOOS, runtime.GOARCH, runtime.Version(), s.sqliteVersion)
	fmt.Printf("VisualWaveDrom is running at %s\n", address)
	if !s.config.noOpen {
		s.clientMu.Lock()
		s.scheduleClientShutdownLocked(clientStartupGracePeriod)
		s.clientMu.Unlock()
	}
	openBrowser(address, s.config.noOpen)
	err = s.httpServer.Serve(listener)
	if errors.Is(err, http.ErrServerClosed) {
		return nil
	}
	return err
}

func main() {
	log.SetFlags(0)
	configuration, err := parseConfig()
	if err != nil {
		log.Fatalf("VisualWaveDrom startup failed: %v", err)
	}
	instance, err := newService(configuration)
	if err != nil {
		log.Fatalf("VisualWaveDrom startup failed: %v", err)
	}
	if configuration.checkRuntime {
		fmt.Printf("Platform:       %s %s\n", runtime.GOOS, runtime.GOARCH)
		fmt.Printf("Server:         Go %s (%s)\n", runtime.Version(), buildVersion)
		fmt.Printf("SQLite:         embedded %s\n", instance.sqliteVersion)
		fmt.Printf("HTML:           %s\n", configuration.htmlPath)
		fmt.Printf("Wave library:   %s\n", configuration.configuredLibrary)
		return
	}
	if err = instance.run(); err != nil {
		log.Fatalf("VisualWaveDrom failed to start: %v", err)
	}
}
